# Generated by Django 3.1.14 on 2025-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('service', 'Service Complaint'), ('account', 'Account & Billing'), ('policy', 'Policies'), ('app', 'Application Issues'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
