# Generated by Django 3.1.14 on 2025-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20250619_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
